### ISSUE TITLE
Lower a specific sound bug

### ISSUE THREAD

**Issue by BorisCryptoWave** [maksim789456/DynamicSurroundingsFabric#1]
I have many issues with sounds which doesn't want to be lowered. It's either 100% or blocked.
It doesn't work well with AmbientSounds. But even for vanilla sounds like Firework launch

**Comment by maksim789456** [comment]
> I have many issues with sounds which doesn't want to be lowered. It's either 100% or blocked.

Yep, sound lowering disable this sound. Try to fix this to the next version
> It doesn't work well with AmbientSounds.

Together work with *AmbientSounds* not guaranteed because ambient sounds will be duplicated. Maybe in future I fix this problem

**Comment by maksim789456** [comment]
Will be fixed in next version
