### ISSUE TITLE
Option to disable the "splash" sound on the title screen

### ISSUE THREAD

**Issue by un-pogaz** [maksim789456/DynamicSurroundingsFabric#12]
A option to disable the "splash" sound at the first appearance of the title screen/opening the game could be nice.

Personally, this kind of startup sound exasperated me to the core.

Thank you for this mod (or maintain this mod apparently), I just discovered it and the game is so much better.

**Comment by maksim789456** [comment]
> A option to disable the "splash" sound at the first appearance of the title screen/opening the game could be nice.

Good idea, I am adding this in next version

> Thank you for this mod (or maintain this mod apparently), I just discovered it and the game is so much better.

🥰

**Comment by maksim789456** [comment]
Added
