### ISSUE TITLE
Game crashes on start up with newest version!

### ISSUE THREAD

**Issue by GenderPretender** [maksim789456/DynamicSurroundingsFabric#18]
for some reason when I have the newest version of dynamic surroundings added it will just crash my game! im on 1.19
The version before it works fine.
[crash-2022-11-25_09.56.18-client.txt](https://github.com/maksim789456/DynamicSurroundingsFabric/files/10094588/crash-2022-11-25_09.56.18-client.txt)

**Comment by maksim789456** [comment]
It's conflict with "Presence Footsteps". Update "Presence Footsteps" to 1.6.3 version to fix this

**Comment by GenderPretender** [comment]
> It's conflict with "Presence Footsteps". Update "Presence Footsteps" to 1.6.3 version to fix this

ok I got it to work but waterfall noises don't work?
