### ISSUE TITLE
All sound seems to be muffled

### ISSUE THREAD

**Issue by svioletg** [maksim789456/DynamicSurroundingsFabric#20]
I've tried to find a setting that might affect this but I can't, couldn't find a related issue (if someone's reported this already and I just couldn't find it, I apologize); after installing the mod it seems like all of the sound coming from the game is noticeably either very muffled or lower quality, is this a bug or have I just not configured something correctly?

**Comment by VanitasFR** [comment]
> I've tried to find a setting that might affect this but I can't, couldn't find a related issue (if someone's reported this already and I just couldn't find it, I apologize); after installing the mod it seems like all of the sound coming from the game is noticeably either very muffled or lower quality, is this a bug or have I just not configured something correctly?

Go in the mod options into "Enhanced Sound Processing" and disable "Enable HRTF"

**Comment by svioletg** [comment]
Seems like that worked, thanks!
