### ISSUE TITLE
Sound effect of frogs interferes

### ISSUE THREAD

**Issue by MarkinhosMLP** [maksim789456/DynamicSurroundingsFabric#26]
PLEASE...... im getting crazy of hearing these fake frogs all the time I EVEN TRIED MODS TO DISABLE THE SOUND BUT IT KEEPS PLAYING AND PLAYING... it is attacking my anxiety every single time i cant... when im in swamp biomes searching for frogs ITS EVEN WORSE cause i get paranoid but i see no frogs aaaaaaaaaaaaaaaaaaa help plz

**Comment by maksim789456** [comment]
To disable frog sounds:

1. Open "Individual Sound Configuration" (set key bind in key binds screen)
2. Search `dsurround:lilypad.bullfrog` and `dsurround:lilypad.frog` sound
3. Mute sounds by volume slider

It should turn out like this:
![image](https://user-images.githubusercontent.com/8225008/214822401-b60e9903-18e1-48e5-9121-cd06efd1af41.png)

**Comment by maksim789456** [comment]
> oh god tysm, i would never knew it... could you please add some information about this in the main page of the mod? so its easier for people to know about it

Added
