### ISSUE TITLE
Weird buzzing most of the time but not always on linux when ESP is turned on

### ISSUE THREAD

**Issue by wiryfuture** [maksim789456/DynamicSurroundingsFabric#3]
When enhanced sound processing is turned on, for me, most of the time, i get a weird buzzing and atrocious audio quality, rendering the mod unusable. 
I've tried using system openal libs and that does not solve it.
On fedora 36 + 1.19.2 and quilt

**Comment by maksim789456** [comment]
I test sound in last quilt version + Arch 5.19.2, everything good
All third-party audio processing is not related to the mod :slightly_smiling_face:

**Comment by wiryfuture** [comment]
Third party audio processing? I was talking about the option in this mod's menu called "enhanced sound processing" 😅

**Comment by maksim789456** [comment]
Ohh, sorry. I didn't understand what you mean at first. I thought about some kind of sound processing in linux

When I test sound in my Arch I had enable ESP in mod and all sound sounded fine.
I can't even imagine why you have such problems when ESP is enabled

**Comment by ham1255** [comment]
sorry for replying to an closed issue, but since i see mention of linux
on my arch based system with that such setting enabled the sound is terrible
