### ISSUE TITLE
Rain game crash

### ISSUE THREAD

**Issue by CursiveTheMeme** [maksim789456/DynamicSurroundingsFabric#5]
While using optifabric, the game crashes when it rains if you have a texture pack on that changes the texture of the rain in some way

[crash-2022-10-02_13.51.04-client.txt](https://github.com/maksim789456/DynamicSurroundingsFabric/files/9693150/crash-2022-10-02_13.51.04-client.txt)

**Comment by maksim789456** [comment]
Will be fixed in next build
