### ISSUE TITLE
Human voices in the background in the sound for ocean biome

### ISSUE THREAD

**Issue by Psychodeus** [maksim789456/DynamicSurroundingsFabric#7]
So, whenever I go to the ocean, I always hear this loop singing "Lupakan dirimu" then echo once more "...dirimu" then goes back to beach ambient, then it goes again and again.
I swear I hear it with my headphones! And I try to find in the .jar the exact .ogg file that have it, but I couldn't find it 😞 
I'm going insane, help!

**Comment by maksim789456** [comment]
wtf, there is exactly no such thing in the sound files responsible for ambient sounds of the beach
You can download and listen to them
Beach ambient: [beach.ogg](https://github.com/maksim789456/DynamicSurroundingsFabric/raw/main/src/main/resources/assets/dsurround/sounds/ambient/outside/beach.ogg)
Ocean ambient: [ocean.ogg](https://github.com/maksim789456/DynamicSurroundingsFabric/raw/main/src/main/resources/assets/dsurround/sounds/ambient/outside/ocean.ogg)

Maybe some other mod add this sounds 🤷‍♂️

**Comment by Psychodeus** [comment]
Why do you close this capybara! There I found it, looks like your .ogg file more clear to hear, it's at 0:04 at beach.ogg 🙄 
Please please fix it, it makes me insane!
![pweeese](https://user-images.githubusercontent.com/93028949/194747023-72889496-2738-4736-9754-bcd9b6353542.png)

**Comment by Psychodeus** [comment]
Well atleast for the online folks, I could take care of this myself in my .jar file, but you, hold the power to change it all!

**Comment by Psychodeus** [comment]
@maksim789456 Yo, I don't know how to make PR, but you can just replace [this](https://ufile.io/ge5limou) to your ocean.ogg it's from [this](https://youtu.be/aUeCnyQi3bQ) trimmed sound.

**Comment by maksim789456** [comment]
> There I found it, it's at 0:04 at ocean.ogg 🙄 Please please fix it, it makes me insane!

Hmmm, u right, I hear some voice. I will replace ocean sound

**Comment by maksim789456** [comment]
Will be replaced in next version
